const $=i=>document.getElementById(i),Y=n=>(n<0?'-':'')+'¥'+Math.abs(Math.round(n)).toLocaleString(),T=Math.trunc;
const S0={nid:100,pb:2,sb:1,sv:60000,
bk:[{id:1,n:'auじぶん',bal:0},{id:2,n:'りそな',bal:0},{id:3,n:'楽天',bal:0},{id:4,n:'SBI',bal:20545}],
si:[[1,'基本月額','g','fix',265000],[2,'手当','g','fix',5000],[3,'残業(単価×時間)','g','hr',1840],[4,'深夜割増(単価×時間)','g','hr',340],[5,'休日出勤(単価×時間)','g','hr',1987],[6,'健康保険','d','fix',15120],[7,'厚生年金','d','fix',27450],[8,'雇用保険(%)','d','rate',.5026],[9,'源泉所得税(%)','d','rate',2.1106],[10,'住民税','d','fix',14800],[11,'定額減税','d','fix',0],[12,'交通・経費','n','mo',0]].map(a=>({id:a[0],n:a[1],t:a[2],m:a[3],v:a[4]})),
bo:{mult:1.9,ms:'6,12',base:1},
bd:[[1,'健康保険(%)','rate',5.04,1,0,''],[2,'厚生年金(%)','rate',9.15,1,0,''],[3,'雇用保険(%)','rate',.5026,0,0,''],[4,'源泉所得税(%・社保後)','rate',2.4737,0,1,'6'],[5,'所得税還付(年末調整)','fix',-13537,0,0,'12']].map(a=>({id:a[0],n:a[1],m:a[2],v:a[3],th:a[4],af:a[5],ms:a[6]})),
tr:[[1,'クレカ引落(auPay)','exp',2,0,0],[2,'クレカ引落(PayPay)','exp',2,0,10000],[3,'別途振込(残・副業)','inc',2,0,0],[4,'SBI振込(予備費)','xf',2,4,0],[5,'旅行貯蓄','xf',2,3,0]].map(a=>({id:a[0],n:a[1],c:a[2],b:a[3],to:a[4],a:a[5]})),
fx:[[1,'住居費+京保険料',30000,25,1,'bank'],[2,'NISA',50000,27,3,'bank'],[3,'マイカー共済(ミラ)',5000,28,2,'bank'],[4,'ティップネス',9460,27,2,'bank'],[5,'iPhone',4439,27,2,'bank','2026-10'],[6,'通信費',2315,10,0,'card'],[7,'Netflix',2290,14,0,'card'],[8,'京(変動予算)',30000,0,0,'card'],[9,'京 健康診断',64000,3,0,'year'],[10,'自動車税',12900,5,0,'year'],[11,'Apple Music',10800,10,0,'year'],[12,'Amazon Prime',5900,10,0,'year'],[13,'FEARNOT',6500,12,0,'year'],[14,'車検(2年)',32000,0,0,'year']].map(a=>({id:a[0],n:a[1],a:a[2],d:a[3],b:a[4],k:a[5],end:a[6]||''})),
m:{'2026-10':{v3:20,t1:300000,t3:60000},'2026-11':{v3:20,v12:1472,t1:100000}},mm:{},
cat:[[201,'交際費(飲み)',5000],[202,'趣味・娯楽(本)',5000],[203,'自動車',0],[204,'交通費',3000],[205,'食費・水道光熱費',0],[206,'日用・消耗品',0]].map(a=>({id:a[0],n:a[1],a:a[2]})),led:[],
big:[['2026-10','ダイコン',25000],['2026-10','ホワイトニング(2)',33000],['2026-10','エジプト航空券',200000],['2026-11','ホワイトニング(3)',33000],['2026-12','ホワイトニング(h)',33000],['2026-12','バリ島航空券',120000],['2026-12','ダイビング',98000],['2027-01','韓国旅費',80000],['2027-03','エジプト旅費',100000],['2027-04','健康診断',65000],['2027-05','ミラ整備関連',100000],['2027-05','バリ島旅費',80000]].map((a,i)=>({id:i+1,ym:a[0],n:a[1],a:a[2],ap:false,pm:'card',b:2,memo:''}))};
let S;try{S=JSON.parse(localStorage.getItem('kk2'))}catch(e){}S=S||JSON.parse(JSON.stringify(S0));S.pays=S.pays||[{id:301,n:'給与',day:25,b:S.pb||2,r:100}];if(S.cb==null)S.cb=S.sb;
mig();const save=()=>{try{localStorage.setItem('kk2',JSON.stringify(S));localStorage.setItem('kk2t',Date.now())}catch(e){}window.onKKSave&&window.onKKSave()};
const now=new Date(),tdy=new Date(now.getFullYear(),now.getMonth(),now.getDate());
function pds(y,day){const[a,b]=y.split('-').map(Number),d=new Date(a,b-1,day),w=d.getDay();if(w==6)d.setDate(d.getDate()-1);if(w==0)d.setDate(d.getDate()-2);return (d.getMonth()+1)+'/'+d.getDate()+'('+'日月火水木金土'[d.getDay()]+')'}
function fp(){return S.pays.find(p=>p.k!='inc')||S.pays[0]}
function pdate(y){const[a,b]=y.split('-').map(Number),d=new Date(a,b-1,(fp()||{day:25}).day),w=d.getDay();if(w==6)d.setDate(d.getDate()-1);if(w==0)d.setDate(d.getDate()-2);return d}
const m0=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');
let ym=tdy>pdate(m0)?now.getFullYear()+'-'+String(now.getMonth()+2>12?1:now.getMonth()+2).padStart(2,'0'):m0;if(tdy>pdate(m0)&&now.getMonth()==11)ym=(now.getFullYear()+1)+'-01';
let tab=0,bs=ym,ym0=ym;
const nx=(y,k=1)=>{let[a,b]=y.split('-').map(Number);b+=k-1;const c=a+Math.floor(b/12),e=((b%12)+12)%12+1;return c+'-'+String(e).padStart(2,'0')};
const mo=y=>+y.slice(5),M=y=>S.m[y]||{},bn=id=>(S.bk.find(b=>b.id==id)||{n:'?'}).n,sum=a=>a.reduce((t,f)=>t+f.a,0);
const inp=(l,id,f,v,t='number')=>`<input type="${t}" ${t=='number'?'inputmode="numeric" step="any"':''} data-p="${l}.${id}.${f}" value="${v}">`;
const sel=(l,id,f,o,v)=>`<select data-p="${l}.${id}.${f}" data-n="${typeof o[0][0]=='number'?1:''}">${o.map(x=>`<option value="${x[0]}" ${x[0]==v?'selected':''}>${x[1]}</option>`).join('')}</select>`;
const BO=()=>S.bk.map(b=>[b.id,b.n]);
const rr=i=>{const R=S.rec.find(r=>r.id==S.ru)||S.rec.slice().sort((a,b)=>a.ym<b.ym?1:-1)[0];if(!R||!R.g)return null;const a=R.v[i.id];return a==null||a===''?null:a/R.g*100};
const val=(i,v,g)=>i.m=='fix'?i.v:i.m=='act'?g*(rr(i)??i.v)/100:i.m=='rate'?g*i.v/100:i.m=='hr'?T(i.v*v(i.id)):v(i.id);
const MM=(y,pj)=>pj?Object.fromEntries(Object.entries(M(ym)).filter(e=>e[0][0]=='v')):M(y);
function sal(y,pj){const m=MM(y,pj),v=i=>+m['v'+i]||0;let g=0,d=0,n=0;S.si.filter(i=>i.t=='g').forEach(i=>g+=val(i,v,0));S.si.forEach(i=>{if(i.t=='d')d+=val(i,v,g);if(i.t=='n')n+=val(i,v,g)});
let bn=0;if(S.bo.ms.split(',').includes(''+mo(y))){const b=((S.si.find(i=>i.id==S.bo.base)||{}).v||0)*S.bo.mult,ok=i=>!i.ms||i.ms.split(',').includes(''+mo(y)),L=S.bd.filter(ok);
const da=L.filter(i=>!i.af).reduce((t,i)=>t+(i.m=='fix'?i.v:i.th?T(T(b/1000)*1000*i.v/100):b*i.v/100),0);bn=b-da-L.filter(i=>i.af).reduce((t,i)=>t+(b-da)*i.v/100,0)}
return{g,net:g-d+n,bn}}
const pdd=()=>(fp()||{day:25}).day,fk=f=>f.k=='year'?f.d||99:f.d?(f.d-pdd()+31)%31:99,ord=L=>S.fo?L:L.slice().sort((a,b)=>fk(a)-fk(b));
const SSEL=(k,v)=>`<select data-p="r.${k}.x" data-n="1"><option value="0" ${v?'':'selected'}>給与口座に残す</option>${BO().map(x=>`<option value="${x[0]}" ${x[0]==v?'selected':''}>${x[1]}</option>`).join('')}</select>`;
const AR=(l,id)=>`<button class="x" onclick="mvL('${l}',${id},-1)">↑</button><button class="x" onclick="mvL('${l}',${id},1)">↓</button>`;
function mvL(l,id,d){const L=S[l],i=L.findIndex(x=>x.id==id),j=i+d;if(j<0||j>=L.length)return;[L[i],L[j]]=[L[j],L[i]];save();go()}
function mvC(id,d){const L=S.cat,i=L.findIndex(x=>x.id==id),j=i+d;if(j<0||j>=L.length)return;[L[i],L[j]]=[L[j],L[i]];save();go()}
function mvF(id,d){const L=S.fx,i=L.findIndex(x=>x.id==id),k=L[i].k;let j=i+d;while(j>=0&&j<L.length&&L[j].k!=k)j+=d;if(j<0||j>=L.length)return;[L[i],L[j]]=[L[j],L[i]];save();go()}
const act=(y,k)=>S.fx.filter(f=>f.k==k&&(!f.end||y<=f.end)),pbank=()=>(fp()||{b:S.bk[0].id}).b;
const bigOf=y=>S.big.filter(b=>b.ym==y).concat(S.fx.filter(f=>f.k=='year'&&f.d==mo(y)).map(f=>({n:f.n+'(年間)',a:f.a,auto:1,ap:f.ap!==false,pm:f.pm,b:f.b,c:f.c})));
function calc(y,op,pj){const m=MM(y,pj),s=sal(y,pj),P=S.pays,pb=pbank(),B={},bg=bigOf(y).filter(b=>b.ap&&(!pj||b.auto)),tr=S.tr.map(t=>({...t,a:m['t'+t.id]!=null?+m['t'+t.id]:t.a})),CD=S.cards.map(k=>({...k,fx:0,bg:0,man:m['c'+k.id]!=null?+m['c'+k.id]:k.a})),cd=id=>CD.find(k=>k.id==id)||CD[0]||{fx:0,bg:0};
S.bk.forEach(b=>B[b.id]={o:op[b.id]||0,out:0,inn:0,xin:0,pay:0,au:0});
let pt=0;const pa={};P.forEach(p=>{if(!B[p.b])return;if(p.k=='inc'){const va=m['p'+p.id]!=null?+m['p'+p.id]:+p.a||0;pa[p.id]=va;B[p.b].inn+=va;pt+=va}else{const v=s.net*p.r/100+(p===fp()?s.bn:0);B[p.b].pay+=v;pt+=v}});
const MF=act(y,'m');MF.forEach(f=>{if(f.pm=='card')cd(f.c).fx+=f.a;else B[f.b]&&(B[f.b].out+=f.a)});
bg.forEach(b=>{if(b.pm=='card')cd(b.c).bg+=b.a;else B[b.b]&&(B[b.b].out+=b.a)});
CD.forEach(k=>{k.tot=k.fx+k.man;B[k.b]&&(B[k.b].out+=k.tot)});
tr.forEach(t=>{if(t.c=='exp'&&B[t.b])B[t.b].out+=t.a;if(t.c=='inc'&&B[t.b])B[t.b].inn+=t.a;if(t.c=='xf'&&B[t.to])B[t.to].xin+=t.a});
const isS=id=>id==pb||B[id].pay>0,mx=tr.filter(t=>t.c=='xf').reduce((t,x)=>t+x.a,0);let au=0;const xo={};S.bk.forEach(b=>{const x=B[b.id];x.au=isS(b.id)?0:Math.max(0,x.out-x.inn);x.sr=b.src&&b.src!=b.id&&B[b.src]?b.src:pb;if(x.sr==pb)au+=x.au;else xo[x.sr]=(xo[x.sr]||0)+x.au});S.bk.forEach(b=>B[b.id].xo=xo[b.id]||0);
const X0=B[pb]||{pay:0,inn:0,out:0},rest=Math.round(X0.pay+X0.inn-X0.out-au-mx);
S.bk.forEach(b=>{const x=B[b.id],k=b.id;x.a=k==pb?x.o+(((rest>=0?S.sb:S.cb)==pb||!(rest>=0?S.sb:S.cb))?rest:0):isS(k)?x.o+x.pay+x.inn+x.xin-x.out-x.xo:x.o+x.inn+x.au+x.xin-x.out-x.xo;x.need=k==pb?x.out-x.inn:x.au+x.xin;if(k!=pb&&((rest>=0&&k==S.sb)||(rest<0&&k==S.cb))){x.a+=rest;if(rest>0)x.need+=rest}});
const delta=S.bk.reduce((t,b)=>t+B[b.id].a-B[b.id].o,0),payInc=Object.values(pa).reduce((t,v)=>t+v,0),bf=sum(MF.filter(f=>f.pm!='card')),cf=sum(MF.filter(f=>f.pm=='card')),cardT=CD.reduce((t,k)=>t+k.tot,0),avail=delta+cardT-S.sv;
return{s,B,rest,tr,bg,cards:CD,bf,cf,avail,free:avail-sum(S.cat),card:CD.reduce((t,k)=>t+k.tot,0),d:delta,payInc,pa,inc:pt+tr.filter(t=>t.c=='inc').reduce((t,x)=>t+x.a,0)}}
const openB=()=>{const o={};S.bk.forEach(b=>o[b.id]=+b.bal||0);return o};
function alloc(c){const pb=pbank(),x=c.B[pb]||{pay:0,inn:0,out:0},av=Math.max(0,x.pay+x.inn-x.out);let r=av;const A={};S.bk.filter(b=>b.id!=pb).map(b=>({b,n:(c.B[b.id].sr==pb?c.B[b.id].au:0)+c.B[b.id].xin})).sort((a,z)=>a.n-z.n).forEach(o=>{const p=Math.min(o.n,r);r-=p;A[o.b.id]={p,c:o.n-p}});const L=S.bk.filter(b=>A[b.id]&&A[b.id].c>0);return{A,rest:c.rest,av,sf:L.reduce((t,b)=>t+A[b.id].c,0),tn:L.map(b=>b.n).join('・')}}
function block(y,c,first){const al=alloc(c);const m=M(y),o=[];S.si.filter(i=>i.m=='hr'||i.m=='mo').forEach(i=>o.push([i.n,'mv.'+y+'.v'+i.id,+m['v'+i.id]||0]));S.pays.filter(p=>p.k=='inc').forEach(p=>o.push([p.n+' 収入('+bn(p.b)+')','mv.'+y+'.p'+p.id,c.pa[p.id]||0]));c.cards.forEach(k=>o.push([`クレカ ${k.n}(${bn(k.b)}引落${k.dd?' '+k.dd+'日':''})`+(k.fx||k.bg?`<div class="mu">${[k.fx?'固定費 '+Y(k.fx)+' を含む':'',k.bg?'大きい出費 '+Y(k.bg):''].filter(Boolean).join('・')}</div>`:''),'ct.'+y+'.'+k.id,Math.round(k.tot)]));S.tr.forEach((t,k)=>o.push([(t.c=='exp'?'−':t.c=='inc'?'+':'→')+' '+t.n,'mv.'+y+'.t'+t.id,c.tr[k].a]));
const sg=t=>c.tr.filter(x=>x.c==t).reduce((s,x)=>s+x.a,0),bc=c.bg.filter(b=>b.pm=='card').reduce((s,b)=>s+b.a,0),bb=c.bg.filter(b=>b.pm!='card').reduce((s,b)=>s+b.a,0);
return`<section><h2>${y.replace('-','年')}月 給与 <span class="mu">${[...new Set(S.pays.map(p=>pds(y,p.day)))].join('・')}</span></h2>${(()=>{const sv=c.rest-sum(S.cat),ng=S.bk.filter(b=>c.B[b.id].a<0).map(b=>b.n),ps=S.pays.filter(p=>p.k!='inc').reduce((t,p)=>t+p.r,0);return`<div class="hero"><div class="mu">今月の貯蓄見込み(余り−日々の予算)</div><div class="big ${sv<0?'ng':'ac'}">${Y(sv)}</div><div class="pg"><i style="width:${Math.max(0,Math.min(100,sv/Math.max(S.sv,1)*100))}%"></i></div></div>${c.rest<0?`<div class="wn">⚠ 給与後が ${Y(-c.rest)} 不足です。補填口座 <select data-p="r.cb.x" data-n="1">${BO().map(x=>`<option value="${x[0]}" ${x[0]==S.cb?'selected':''}>${x[1]}</option>`).join('')}</select> から補填します</div>`:''}${ng.length?`<div class="wn">⚠ 給与後の残高がマイナス: ${ng.join('、')}</div>`:''}${ps!=100?`<div class="wn">⚠ 給与の振込割合の合計が ${ps}% です。副業などの収入は、設定タブで「副業・その他(金額)」の種類にしてください</div>`:''}`})()}<div class="big ac">${Y(c.s.net)}</div><div class="mu">手取り(総支給 ${Y(c.s.g)})</div>${c.s.bn?`<p>賞与手取り <b>${Y(c.s.bn)}</b></p>`:''}
<div class="w"><table>${o.map(r=>`<tr><td>${r[0]}</td><td class="r"><input type="number" inputmode="numeric" step="any" data-p="${r[1]}" value="${r[2]}"></td></tr>`).join('')}</table></div>
<h3>収支の内訳</h3><table><tr><td>給与手取り${c.s.bn?'+賞与':''}</td><td class="r">${Y(c.s.net+c.s.bn)}</td></tr>${S.pays.filter(p=>p.k=='inc').map(p=>`<tr><td>+ ${p.n}</td><td class="r ac">${Y(c.pa[p.id]||0)}</td></tr>`).join('')}<tr><td>+ 収入項目</td><td class="r ac">${Y(sg('inc'))}</td></tr><tr class="tot"><td>= 収入合計</td><td class="r">${Y(c.inc)}</td></tr><tr><td>− 固定費(銀行引落)</td><td class="r">${Y(c.bf)}</td></tr><tr><td>− 支出項目</td><td class="r">${Y(sg('exp'))}</td></tr><tr><td>− クレカ引落(合計)</td><td class="r">${Y(c.cards.reduce((t,k)=>t+k.tot,0))}</td></tr><tr><td>− 大きい出費(銀行)</td><td class="r">${Y(bb)}</td></tr><tr><td>→ 振替項目</td><td class="r">${Y(sg('xf'))}</td></tr>
<tr class="tot"><td>= 支出合計(振替含む)</td><td class="r">${Y(c.inc-c.rest)}</td></tr><tr class="tot"><td>${c.rest<0?'不足(補填口座から)':'余り → '+SSEL('sb',S.sb)}</td><td class="r ${c.rest<0?'ng':'ac'}">${Y(c.rest)}</td></tr></table>
<h3>銀行別 残高</h3><div class="mu">振替可能額 ${Y(al.av)}(給与+収入−給与口座の引落)${al.sf>0?` / 不足 ${Y(al.sf)} は ${bn(S.cb)} → ${al.tn} へ1回で振替`:''}</div><div class="w"><table><tr><th>口座</th><th class="r">${first?'現在残高':'開始残高'}</th><th class="r">振替合計</th><th class="r">給与後</th></tr>${S.bk.map(b=>`<tr><td>${b.n}${S.pays.some(p=>p.b==b.id)?' <span class="mu">給与口座</span>':''}</td><td class="r">${first?inp('bk',b.id,'bal',b.bal):Y(c.B[b.id].o)}</td><td class="r">${Y(c.B[b.id].need)}${al.A[b.id]&&al.A[b.id].c>0?`<div class="mu">給与から ${Y(al.A[b.id].p)}<br>${bn(S.cb)}から ${Y(al.A[b.id].c)}</div>`:''}${al.sf>0&&b.id==S.cb?`<div class="mu">${al.tn}へ ${Y(al.sf)} を振替</div>`:''}${c.B[b.id].au>0&&c.B[b.id].sr!=pbank()?`<div class="mu">${bn(c.B[b.id].sr)}から ${Y(c.B[b.id].au)}</div>`:''}${c.B[b.id].xo>0?`<div class="mu">他口座へ ${Y(c.B[b.id].xo)} を振替</div>`:''}</td><td class="r big2 ${c.B[b.id].a<0?'ng':''}">${Y(c.B[b.id].a)}</td></tr>`).join('')}</table></div>
</section>`}
const chain=y=>{let op=openB();const ap=k=>{const o=(S.ob||{})[k];if(o)Object.keys(o).forEach(id=>{if(o[id]!=='')op[id]=+o[id]})};for(let k=ym0,n=0;k<y&&n<36;k=nx(k),n++){if(k>ym0)ap(k);const c=calc(k,op);op=Object.fromEntries(S.bk.map(b=>[b.id,c.B[b.id].a]))}if(y>ym0)ap(y);return op};
function clrOb(y,id){if(S.ob&&S.ob[y])delete S.ob[y][id];save();go()}
const fd=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'),catName=c=>c?(S.cat.find(k=>k.id==c)||{n:'?'}).n:'自由資金';
const cutD=()=>+S.cut||15,pStart=y=>{const[a,b]=y.split('-').map(Number);return fd(new Date(a,b-2,cutD()+1))},pEnd=y=>{const[a,b]=y.split('-').map(Number);return fd(new Date(a,b-1,cutD()))},inP=(d,y)=>d>=pStart(y)&&d<=pEnd(y),ml0=fd(tdy)>pEnd(m0)?nx(m0):m0;
const mstrip=()=>{if(ym<bs||ym>nx(bs,11))bs=ym;return`<div class="f"><button class="mb" onclick="bs=nx(bs,-12);ym=nx(ym,-12);go()">◀</button><button class="mb" onclick="bs=nx(bs,12);ym=nx(ym,12);go()">▶</button></div><div class="ms4">${[...Array(12).keys()].map(i=>{const y=nx(bs,i);return`<button class="mb ${y==ym?'on':''}" onclick="ym='${y}';go()">${y.slice(2,4)}/${mo(y)}月</button>`}).join('')}</div>`};
function kpi(){const dn=pdate(ym0),days=Math.max(1,Math.round((dn-tdy)/864e5)),lp=pStart(ml0),nd=pEnd(ml0),L=S.led.filter(l=>l.d>=lp&&l.d<=nd),sp=L.reduce((t,l)=>t+l.a,0),cs=L.filter(l=>l.c).reduce((t,l)=>t+l.a,0),bm=ml0,c0=calc(bm,chain(bm)),n1=nx(ym0),c1=calc(n1,chain(n1)),rem=c0.avail-c0.card-sp,bl=Math.min(sum(S.cat)-cs,rem),fl=rem-Math.max(0,sum(S.cat)-cs),nx1=c1.d-sum(S.cat),tot=S.bk.reduce((t,b)=>t+(+b.bal||0),0),k=(l,v,c,m)=>`<div class="k ${m||''}"><span>${l}</span><b class="${c||''}">${v}</b></div>`;
return`<div class="kp">${k('今月あと使える金額',Y(rem),rem<0?'ng':'ac','main')}${k('1日あたり',Y(rem/days),rem<0?'ng':'')}${k('次回給与まで',days+'日')}${k('現在の総資産',Y(tot))}${k('予算の残り',Y(bl),bl<0?'ng':'')}${k('自由資金',Y(fl),fl<0?'ng':'')}${k('来月の増減予想',Y(nx1),nx1<0?'ng':'ac')}</div>`}
function flowRows(c,x){const oth=c.inc-c.bf-c.card-c.d,R=[['収入合計',c.inc],['− 固定費(銀行)',-c.bf],['− その他支出(大きい出費等)',-oth],['− 毎月の貯金',-S.sv],['= 利用可能額',c.avail],['− 日々の予算',-sum(S.cat)],['= 自由資金',c.free],['− クレカ引落(合計)',-c.card],['= 今月の収支',c.avail-c.card]].concat(x||[]),mx=Math.max(1,c.inc);
return R.map(r=>`<div class="tr fl"><span>${r[0]}</span><div class="br"><i class="${r[1]<0?'neg':''}" style="width:${Math.min(100,Math.abs(r[1])/mx*100)}%"></i></div><b class="${r[1]<0?'ng':'ac'}">${Y(r[1])}</b></div>`).join('')}
function flow(c){return`<section><h2>お金の流れ ${ym.replace('-','年')}月</h2>${flowRows(c)}<div class="mu">今月の収支 = 利用可能額 − クレカ引落(合計)。口座間の振替・投資は資産の移動なので支出に含めません</div></section>`}
function bankPanel(c,first){const al=alloc(c);return`<section><h2>銀行別 残高</h2><div class="mu">振替可能額 ${Y(al.av)}${al.sf>0?` / 不足 ${Y(al.sf)} は ${bn(S.cb)} → ${al.tn} へ1回で振替`:''}</div><div class="bt">${S.bk.map(b=>{const x=c.B[b.id],a=al.A[b.id];return`<div class="bt1"><div class="n">${b.n}${S.pays.filter(p=>p.b==b.id).map(p=>`<i>${p.n}</i>`).join('')}</div><div class="r"><span>${first?'現在残高':'開始残高'}</span>${first?inp('bk',b.id,'bal',b.bal):`<input type="number" inputmode="numeric" data-p="ob.${ym}.${b.id}" value="${Math.round(x.o)}">${((S.ob||{})[ym]||{})[b.id]!=null&&((S.ob||{})[ym]||{})[b.id]!==''?`<button class="x" onclick="clrOb('${ym}',${b.id})">↺</button>`:''}`}</div><div class="r"><span>振替合計</span><b>${Y(x.need)}</b></div>${S.pays.filter(p=>p.b==b.id).map(p=>`<div class="r"><span>${p.n}</span><b>+${Y(p.k=='inc'?(c.pa[p.id]||0):c.s.net*p.r/100+(p===fp()?c.s.bn:0))}</b></div>`).join('')}${a&&a.c>0?`<div class="mu">給与から ${Y(a.p)} + ${bn(S.cb)}から ${Y(a.c)}</div>`:''}${al.sf>0&&b.id==S.cb?`<div class="mu">${al.tn}へ ${Y(al.sf)} を振替</div>`:''}${x.au>0&&x.sr!=pbank()?`<div class="mu">${bn(x.sr)}から ${Y(x.au)}</div>`:''}${x.xo>0?`<div class="mu">他口座へ ${Y(x.xo)} を振替</div>`:''}${al.rest>0&&b.id==S.sb&&b.id!=pbank()?`<div class="mu">余り +${Y(al.rest)} を受入</div>`:''}<div class="af ${x.a<0?'ng':''}"><span>給与後</span>${Y(x.a)}</div></div>`}).join('')}</div></section>`}
function pay(){const c=calc(ym,chain(ym)),h=block(ym,c,ym==ym0),i1=h.indexOf('<h3>収支の内訳</h3>'),i2=h.indexOf('<h3>銀行別 残高</h3>');
return`<div class="cols"><div>${h.slice(0,i1)}</section></div><div><section><h2>収支の内訳</h2>${h.slice(i1+14,i2)}</section>${flow(c)}</div><div>${bankPanel(c,ym==ym0)}</div></div>`}
const del=(l,id)=>{S[l]=S[l].filter(x=>x.id!=id);save();go()},add=(l,o)=>{S[l].push({id:++S.nid,...o});save();go()};
const X=(l,id)=>`<button class="x" onclick="del('${l}',${id})">×</button>`;
const TY=[['g','支給(総支給に含む)'],['d','控除(引く)'],['n','手取りに加算(交通費など)']],MD=[['act','実績比率(比率表)'],['fix','固定額'],['rate','総支給×%'],['hr','単価×時間(月ごと入力)'],['mo','月ごとに入力']];
function setTab(){const bo=(k,v)=>`<select data-p="r.${k}.x" data-n="1">${BO().map(x=>`<option value="${x[0]}" ${x[0]==v?'selected':''}>${x[1]}</option>`).join('')}</select>`,it=(h)=>`<div class="it">${h}</div>`,sc=(t,b,o)=>`<details class="sc" data-t="${t}" ${(OPN[t]??!!o)?'open':''}><summary>${t}</summary>${b}</details>`,L=(t,h)=>`<label>${t} ${h}</label>`;
return`<div class="col">`+
sc('給与・副業など収入の振込(日付・口座・金額)',S.pays.map(p=>it('<div class="r1">'+inp('pays',p.id,'n',p.n,'text')+X('pays',p.id)+'</div><div class="r2">'+sel('pays',p.id,'k',[['sal','給与(手取り×割合)'],['inc','副業・その他(金額)']],p.k||'sal')+L('日',inp('pays',p.id,'day',p.day))+L('口座',sel('pays',p.id,'b',BO(),p.b))+(p.k=='inc'?L('金額',inp('pays',p.id,'a',p.a||0)):L('割合%',inp('pays',p.id,'r',p.r)))+'</div>')).join('')+`<p class="mu">給与が月に複数回、または複数の口座に入る場合は行を追加し、割合(手取りに対する%)の合計を100%にします。1行目が中心口座で、賞与の振込先と、他口座への振替の資金元になります。</p><button class="b" onclick="add('pays',{n:'給与',k:'sal',day:25,b:S.bk[0].id,r:0})">給与を追加</button> <button class="b" onclick="add('pays',{n:'副業',k:'inc',day:25,b:S.bk[0].id,r:0,a:0})">副業・収入を追加</button>`)+
sc('口座・貯蓄・補填',S.bk.map(b=>it('<div class="r1">'+inp('bk',b.id,'n',b.n,'text')+AR('bk',b.id)+X('bk',b.id)+'</div><div class="r2">'+L('不足時の振替元',sel('bk',b.id,'src',[[0,'給与口座']].concat(BO()),b.src||0))+'</div>')).join('')+`<button class="b" onclick="add('bk',{n:'新しい口座',bal:0})">口座を追加</button><div class="it">${L('余りの貯蓄先',bo('sb',S.sb))}${L('不足時の補填口座',bo('cb',S.cb))}${L('毎月の貯金額',`<input type="number" inputmode="numeric" data-p="r.sv.x" value="${S.sv}">`)}</div>`)+
sc('クレジットカード',S.cards.map(k=>it(inp('cards',k.id,'n',k.n,'text')+L('引落口座',sel('cards',k.id,'b',BO(),k.b))+L('引落日',inp('cards',k.id,'dd',k.dd||''))+L('利用額の初期値',inp('cards',k.id,'a',k.a))+AR('cards',k.id)+X('cards',k.id))).join('')+`<button class="b" onclick="add('cards',{n:'新しいカード',b:pbank(),a:0})">カードを追加</button>`)+
 sc('給与の項目・実績比率',S.si.map(i=>it('<div class="r1">'+inp('si',i.id,'n',i.n,'text')+inp('si',i.id,'v',i.v)+X('si',i.id)+'</div><div class="r2">'+sel('si',i.id,'t',TY,i.t)+sel('si',i.id,'m',MD,i.m)+'</div>')).join('')+`<button class="b" onclick="add('si',{n:'新しい項目',t:'g',m:'fix',v:0})">給与項目を追加</button>`+ratioTab().replace(/^<section><h2>.*?<\/h2>/,'<h3>実績比率の計算表</h3>').replace(/<\/section>$/,''))+
sc('賞与',`<div class="it">${L('倍率',`<input type="number" step="any" data-p="o.bo.mult" value="${S.bo.mult}">`)}${L('支給月',`<input type="text" data-p="o.bo.ms" value="${S.bo.ms}" style="width:80px">`)}${L('基準',`<select data-p="o.bo.base" data-n="1">${S.si.map(i=>`<option value="${i.id}" ${i.id==S.bo.base?'selected':''}>${i.n}</option>`).join('')}</select>`)}</div>`+S.bd.map(i=>it(inp('bd',i.id,'n',i.n,'text')+sel('bd',i.id,'m',[['fix','固定額'],['rate','%']],i.m)+inp('bd',i.id,'v',i.v)+L('適用月',inp('bd',i.id,'ms',i.ms,'text'))+X('bd',i.id))).join('')+`<p class="mu">適用月が空欄なら毎回、6 や 12 なら その月だけ計算します。</p><button class="b" onclick="add('bd',{n:'新しい控除',m:'fix',v:0,th:0,af:0,ms:''})">賞与の控除を追加</button>`)+
sc('給与・振替の項目',`<p class="mu">支出=マイナス、収入=プラス、振替=給与の中心口座から別口座へ移す計算です。金額は各月の画面で入力します。</p>`+S.tr.map(t=>it(inp('tr',t.id,'n',t.n,'text')+sel('tr',t.id,'c',[['exp','支出−'],['inc','収入+'],['xf','振替→']],t.c)+L(t.c=='xf'?'振替先':'口座',t.c=='xf'?sel('tr',t.id,'to',BO(),t.to):sel('tr',t.id,'b',BO(),t.b))+L('初期金額',inp('tr',t.id,'a',t.a))+X('tr',t.id))).join('')+`<button class="b" onclick="add('tr',{n:'新しい項目',c:'exp',b:S.bk[0].id,to:S.bk[0].id,a:0})">項目を追加</button>`)+sc('アプリの使い方',`<div class="mu" style="line-height:1.9">①設定: 給与の振込(日・口座・割合)、口座、給与の項目、賞与、給与・振替の項目、カードを自分用に整えます。<br>②比率表: 給与明細の実績を入力し「予定に反映」すると、保険料・税を総支給×実績比率で予測します。<br>③固定費: 銀行引落かクレカかを選びます。クレカの固定費はカードの引落額に自動で入ります。並びは給与日から昇順(手動に切替可)。<br>④給与・振替: 月ごとの残業時間・カード利用額・収入/支出/振替を入力します。手取り+収入−支出=差引で、不足なら赤で警告します。銀行別残高は「開始残高+給与+収入−引落−振替」です。<br>⑤家計簿: 基準の給与(既定は翌月分)から 手取り−貯金−固定費=利用可能、そこから各予算を引いた残りが自由資金です。日々の支出はここに記録します。<br>⑥大きい出費: 月ごとに予定とメモを管理します。銀行引落で「給与に反映」すると給与・振替の支出に入ります。クレカ払いはカード欄に金額の目安を表示するだけで、合計は自動で増えません。<br>⑦貯蓄推移: 1か月目は入力どおり、2か月目以降は確定していない出費を除いた予想です。<br>⑧保存: データはこの端末のブラウザに保存されます。別端末へはバックアップの文字列で移します。</div>`)+`</div>${bak()}`}
function fixedTab(){const tg=f=>f.pm=='card'?sel('fx',f.id,'c',S.cards.map(k=>[k.id,k.n]),f.c):sel('fx',f.id,'b',BO(),f.b),
row=f=>`<div class="it fx"><div class="r1">${inp('fx',f.id,'n',f.n,'text')}${inp('fx',f.id,'a',f.a)}${S.fo?`<button class="x" onclick="mvF(${f.id},-1)">↑</button><button class="x" onclick="mvF(${f.id},1)">↓</button>`:''}${X('fx',f.id)}</div><div class="r2">${sel('fx',f.id,'pm',[['bank','銀行引落'],['card','クレカ']],f.pm)}${tg(f)}<label>${f.k=='year'?'月':'日'}${inp('fx',f.id,'d',f.d)}</label>${f.k=='year'?`<label><input type="checkbox" data-p="fx.${f.id}.ap" ${f.ap?'checked':''}>給与に反映</label>`:`<label>終了月${inp('fx',f.id,'end',f.end||'','month')}</label>`}</div></div>`,M1=act(ym,'m'),Y1=S.fx.filter(f=>f.k=='year');
return`<div class="g"><section><h2>月の固定費</h2><label><input type="checkbox" data-p="r.fo.x" ${S.fo?'checked':''}> 並び順を手動にする(OFFは給与日から昇順)</label><div class="mu">${ym.replace('-','年')}月 銀行引落 ${Y(sum(M1.filter(f=>f.pm!='card')))} / クレカ ${Y(sum(M1.filter(f=>f.pm=='card')))}</div>${ord(S.fx.filter(f=>f.k=='m')).map(row).join('')}<button class="b" onclick="addF('m')">固定費を追加</button></section><section><h2>年間引落</h2>${ord(Y1).map(row).join('')}<div class="mu">月換算 ${Y(sum(Y1)/12)}。引落月に、選んだ支払い方法で給与予定へ自動反映します。</div><button class="b" onclick="addF('year')">年間引落を追加</button></section></div>`}
function led(){const L=S.led.filter(l=>inP(l.d,ym)).sort((a,b)=>b.d.localeCompare(a.d)),bm=ym,c=calc(bm,chain(bm)),spAll=L.reduce((t,l)=>t+l.a,0),sp=k=>L.filter(l=>l.c==k).reduce((t,l)=>t+l.a,0),td=fd(tdy);
return`<div class="g"><section><h2>${ym.replace('-','年')}月 予算と残り</h2><div class="mu">基準の給与: ${bm.replace('-','年')}月給与(当月) / 管理期間 ${pStart(ym).slice(5)}～${pEnd(ym).slice(5)} <label>締め日 <input type="number" data-p="r.cut.x" value="${cutD()}" style="width:50px">日</label></div>${mstrip()}${flowRows(c,[['− 日々の支出(実績)',-spAll],['= 支出込みの今月の収支',c.avail-c.card-spAll]])}<div class="w"><table><tr><th>項目</th><th class="r">予定</th><th class="r">実績</th><th class="r">差額</th><th></th></tr>${S.cat.map(k=>`<tr><td>${inp('cat',k.id,'n',k.n,'text')}</td><td class="r">${inp('cat',k.id,'a',k.a)}</td><td class="r">${Y(sp(k.id))}</td><td class="r ${k.a-sp(k.id)<0?'ng':''}">${Y(k.a-sp(k.id))}</td><td style="white-space:nowrap"><button class="x" onclick="mvC(${k.id},-1)">↑</button><button class="x" onclick="mvC(${k.id},1)">↓</button>${X('cat',k.id)}</td></tr>`).join('')}
<tr class="tot"><td>項目合計</td><td class="r">${Y(sum(S.cat))}</td><td class="r">${Y(S.cat.reduce((t,k)=>t+sp(k.id),0))}</td><td class="r">${Y(sum(S.cat)-S.cat.reduce((t,k)=>t+sp(k.id),0))}</td><td></td></tr><tr><td>自由資金(余り)</td><td class="r">${Y(c.free)}</td><td class="r">${Y(sp(0))}</td><td class="r ${c.free-sp(0)<0?'ng':'ac'}">${Y(c.free-sp(0))}</td><td></td></tr></table></div><button class="b" onclick="add('cat',{n:'新しい項目',a:0})">項目を追加</button></section>
<section><h2>支出を記録</h2><div class="f"><input type="date" id="ld" value="${inP(td,ym)?td:pStart(ym)}"><select id="lc">${S.cat.map(k=>`<option value="${k.id}">${k.n}</option>`).join('')}<option value="0">自由資金</option></select><input type="number" id="la" onkeydown="if(event.key=='Enter')addL()" placeholder="金額" inputmode="numeric"><input type="text" id="lm" onkeydown="if(event.key=='Enter')addL()" placeholder="メモ"><button class="b" onclick="addL()">記録</button></div>
${recent()}<div class="w"><table>${L.map(l=>`<tr><td>${l.d.slice(5)}</td><td>${l.c?(S.cat.find(k=>k.id==l.c)||{n:'?'}).n:'自由資金'}<div class="mu">${l.m||''}</div></td><td class="r">${Y(l.a)}</td><td>${X('led',l.id)}</td></tr>`).join('')||'<tr><td class="mu">この月の記録はまだありません</td></tr>'}</table></div></section></div>`}
function bigTab(){if(ym<bs||ym>nx(bs,11))bs=ym;const L=bigOf(ym),ov=[0,1,2,3,4,5,6,7,8,9,10,11].map(i=>{const y=nx(bs,i);return`<button class="mb ${y==ym?'on':''}" onclick="ym='${y}';go()">${y.slice(2,4)}/${mo(y)}月<br><span class="mu">${Y(bigOf(y).reduce((t,b)=>t+b.a,0))}</span></button>`}).join('');
return`<section><h2>${ym.replace('-','年')}月の大きい出費 <span class="mu">計 ${Y(L.reduce((t,b)=>t+b.a,0))}</span></h2><div class="f"><button class="mb" onclick="bs=nx(bs,-12);ym=nx(ym,-12);go()">◀ 前の12か月</button><button class="mb" onclick="bs=nx(bs,12);ym=nx(ym,12);go()">次の12か月 ▶</button></div><div class="ms4">${ov}</div>
<div class="w"><table>${L.map(b=>b.auto?`<tr><td>${b.n}</td><td class="r">${Y(b.a)}</td><td colspan=3 class="mu">年間引落から自動</td></tr>`:`<tr><td>${inp('big',b.id,'n',b.n,'text')}</td><td class="r">${inp('big',b.id,'a',b.a)}</td><td>${sel('big',b.id,'pm',[['card','クレカ払い'],['bank','銀行引落']],b.pm)}</td><td>${b.pm=='card'?sel('big',b.id,'c',S.cards.map(k=>[k.id,k.n]),b.c):sel('big',b.id,'b',BO(),b.b)}</td><td><label><input type="checkbox" data-p="big.${b.id}.ap" ${b.ap?'checked':''}> 給与に反映</label></td><td>${X('big',b.id)}</td></tr><tr><td colspan=6>${inp('big',b.id,'memo',b.memo||'','text')}</td></tr>`).join('')||'<tr><td class="mu">この月の予定はありません</td></tr>'}</table></div>
<div class="f"><input type="text" id="bn" placeholder="予定の名前"><input type="number" id="ba" placeholder="金額" inputmode="numeric"><button class="b" onclick="addB()">追加</button></div><div class="mu">口座欄は、クレカなら引落される口座、銀行引落なら引落口座です。反映すると、その月の給与・振替の計算に入ります。</div>
<h3>この月のメモ</h3><textarea data-p="o.mm.${ym}" placeholder="メモ">${S.mm[ym]||''}</textarea></section>`}
function tgAct(id){const i=S.si.find(x=>x.id==id);if(i.m!='act'){i.m0=i.m;i.v0=i.v;if(i.m=='fix')i.v=0;i.m='act'}else{i.m=i.m0||'rate';if(i.v0!=null)i.v=i.v0}save();go()}
function ratioTab(){const D=S.si.filter(i=>i.t=='d'),g=sal(ym).g,pc=(r,i)=>r.g&&r.v[i.id]!=null&&r.v[i.id]!==''?(r.v[i.id]/r.g*100).toFixed(4)+'%':'—';
return`<section><h2>給与実績の比率計算表</h2><div class="mu">給与明細の実績を入力すると、控除ごとの比率(控除額÷総支給)を計算します。「予定に反映」にチェックした項目は、月の給与予定で 総支給×この比率 として計算します。</div><div class="w"><table><tr><th>月</th><th>総支給</th>${D.map(i=>`<th>${i.n}<br><label><input type="checkbox" ${i.m=='act'?'checked':''} onchange="tgAct(${i.id})">予定に反映</label></th>`).join('')}<th></th></tr>${S.rec.map(r=>`<tr><td>${inp('rec',r.id,'ym',r.ym,'month')}</td><td>${inp('rec',r.id,'g',r.g)}</td>${D.map(i=>`<td><input type="number" inputmode="numeric" data-p="rv.${r.id}.${i.id}" value="${r.v[i.id]??''}"><div class="mu">${pc(r,i)}</div></td>`).join('')}<td>${X('rec',r.id)}</td></tr>`).join('')}</table></div><button class="b" onclick="add('rec',{ym:ym,g:0,v:{}})">実績を追加</button>
<div class="f"><label>反映する記録 <select data-p="r.ru.x" data-n="1"><option value="0">最新の月</option>${S.rec.map(r=>`<option value="${r.id}" ${r.id==S.ru?'selected':''}>${r.ym}</option>`).join('')}</select></label></div>
<h3>${ym.replace('-','年')}月の予定(総支給 ${Y(g)})</h3><table>${D.map(i=>{const r=rr(i);return`<tr><td>${i.n}</td><td class="mu">${i.m=='act'?(r==null?'実績なし・設定値':'実績比率'):'設定どおり'}</td><td class="r">${r==null?'—':r.toFixed(4)+'%'}</td><td class="r">${Y(val(i,()=>0,g))}</td></tr>`}).join('')}</table></section>`}
const OPN={};
const spark=v=>{const mn=Math.min(...v),mx=Math.max(...v),h=mx-mn||1,P=v.map((x,i)=>[20+i*560/(v.length-1),75-(x-mn)/h*60]);return`<svg viewBox="0 0 600 90" style="width:100%;height:auto"><polyline fill="none" stroke="var(--gd)" stroke-width="2" points="${P.map(p=>p.join(',')).join(' ')}"/>${P.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3" fill="var(--gd)"/>`).join('')}<text x="20" y="10" fill="var(--mu)" font-size="11">${Y(mx)}</text><text x="20" y="88" fill="var(--mu)" font-size="11">${Y(mn)}</text></svg>`};
let ts=0;
function trend(){if(ts&&!S.bk.some(b=>b.id==ts))ts=0;const pb=pbank(),o0=chain(ym),dl=y=>Math.max(S.led.filter(l=>inP(l.d,y)).reduce((t,l)=>t+l.a,0),sum(S.cat));let op=o0,cum=0;const R=[];
for(let i=0;i<12;i++){const y=nx(ym,i);let bal;
if(i<2){const c=calc(y,op);bal=Object.fromEntries(S.bk.map(b=>[b.id,c.B[b.id].a-(b.id==pb?dl(y):0)]))}else bal=Object.fromEntries(S.bk.map(b=>[b.id,op[b.id]+(R[1].bal[b.id]-o0[b.id])/2]));
const sv=S.bk.reduce((t,b)=>t+bal[b.id]-op[b.id],0);cum+=sv;R.push({y,sv,cum,bal,est:i>=2,tot:S.bk.reduce((t,b)=>t+bal[b.id],0)});op=bal}
const avg=(R[0].sv+R[1].sv)/2,cl=v=>v<0?'ng':'ac',
chips=`<div class="ms"><button class="mb ${ts?'':'on'}" onclick="ts=0;go()">全口座</button>${S.bk.map(b=>`<button class="mb ${ts==b.id?'on':''}" onclick="ts=${b.id};go()">${b.n}</button>`).join('')}</div>`,
L=r=>r.y.slice(2,4)+'/'+mo(r.y)+'月'+(r.est?'予':''),
bars=a=>{const mx=Math.max(1,...a.map(v=>Math.abs(v.v)));return a.map(r=>`<div class="tr"><span>${r.l}</span><div class="br"><i class="${r.v<0?'neg':''}" style="width:${Math.abs(r.v)/mx*100}%"></i></div><b class="${cl(r.v)}">${Y(r.v)}</b></div>`).join('')},
note='<div class="mu">増減 = 収支 − 日々の出費。「予」は今月・来月の平均が続く予想</div>';
if(ts){const b=S.bk.find(x=>x.id==ts);let p=+b.bal||0;return`<div class="g"><section><h2>貯蓄推移</h2>${chips}${note}<div class="mu">${b.n} 現在残高 ${Y(p)}</div>${bars(R.map(r=>({l:L(r),v:r.bal[ts]})))}</section><section><h2>月別の増減</h2><div class="w"><table><tr><th>月</th><th class="r">残高</th><th class="r">増減</th></tr>${R.map(r=>{const d=r.bal[ts]-p;p=r.bal[ts];return`<tr><td>${L(r)}</td><td class="r">${Y(r.bal[ts])}</td><td class="r ${cl(d)}">${Y(d)}</td></tr>`}).join('')}</table></div></section></div>`}
return`<div class="g"><section><h2>貯蓄推移</h2>${chips}<div class="hero"><div class="mu">今月 ${Y(R[0].sv)} / 来月 ${Y(R[1].sv)} → 平均 ${Y(avg)}/月</div><div class="mu">このままだと12か月後の貯蓄(予想)</div><div class="big ${cl(R[11].cum)}">${Y(R[11].cum)}</div><div class="mu">6か月後 ${Y(R[5].cum)}</div></div>${note}<div class="mu">総資産の推移 / 3か月後の予想 ${Y(R[2].tot)}${R[1].sv<0?' ⚠ 来月は赤字予定':''}</div>${spark(R.map(r=>r.tot))}${bars(R.map(r=>({l:L(r),v:r.cum})))}</section><section><h2>月別の増減と口座残高</h2><div class="w"><table><tr><th>月</th><th class="r">増減</th>${S.bk.map(b=>`<th class="r">${b.n}</th>`).join('')}<th class="r">合計</th></tr>${R.map(r=>`<tr><td>${L(r)}</td><td class="r ${cl(r.sv)}">${Y(r.sv)}</td>${S.bk.map(b=>`<td class="r">${Y(r.bal[b.id])}</td>`).join('')}<td class="r">${Y(r.tot)}</td></tr>`).join('')}</table></div></section></div>`}
function mig(){if(!S.cards){S.cards=[];[[1,401],[2,402]].forEach(a=>{const t=S.tr.find(x=>x.id==a[0]&&/クレカ/.test(x.n));if(t){S.cards.push({id:a[1],n:t.n.replace(/クレカ引落|[()]/g,'')||'カード',b:t.b,a:t.a});Object.values(S.m).forEach(mm=>{if(mm['t'+a[0]]!=null){mm['c'+a[1]]=mm['t'+a[0]];delete mm['t'+a[0]]}});S.tr=S.tr.filter(x=>x!==t)}});if(!S.cards.length)S.cards=[{id:401,n:'カード',b:S.pays[0]?S.pays[0].b:1,a:0}]}
const pb=S.pays[0]?S.pays[0].b:1;S.fx.forEach(f=>{if(f.pm)return;f.pm=f.k=='card'?'card':'bank';f.c=S.cards[0].id;if(f.k=='year'){f.ap=true;f.b=pb}else f.k='m';if(f.pm=='card')f.b=pb});
S.big.forEach(b=>{if(b.c==null)b.c=S.cards[0].id});
if(!S.rec){S.rec=[{id:501,ym:'2026-09',g:299440,v:{8:1505,9:6320}}];S.ru=0;S.si.forEach(i=>{if(i.id==8||i.id==9){i.m0=i.m;i.v0=i.v;i.m='act'}})}}
function bak(){return`<section style="margin-top:12px"><h2>バックアップ(スマホ↔PC移行)</h2><div class="mu">データはこの端末のブラウザに保存されます。別の端末へは、書き出した文字列を貼り付けて読み込みます。</div><textarea id="bkt"></textarea><div class="f"><button class="b" onclick="bkt.value=JSON.stringify(S)">書き出し</button><button class="b" onclick="try{S=JSON.parse(bkt.value);save();go()}catch(e){alert('読み込めませんでした。文字列全体を貼り付けてください')}">読み込み</button></div></section>`}
function go(){$('ym').value=ym;$('nav').innerHTML=['給与・振替','固定費','家計簿','大きい出費','貯蓄推移','設定'].map((t,i)=>`<button class="${i==tab?'on':''}" onclick="tab=${i};if(${i}==2&&ym==ym0)ym=ml0;else if(${i}!=2&&ym==ml0)ym=ym0;go()">${t}</button>`).join('');
$('app').innerHTML=kpi()+[pay,fixedTab,led,bigTab,trend,setTab][tab]()}
function mv(k){ym=nx(ym,k);go()}$('ym').onchange=e=>{if(e.target.value){ym=e.target.value;go()}};
function addF(k){add('fx',{n:'新しい固定費',a:0,d:k=='m'?25:1,k,pm:'bank',b:pbank(),c:S.cards[0]?S.cards[0].id:0,end:'',ap:true})}
const recent=()=>{const seen=new Set(),r=[];S.led.slice().reverse().forEach(l=>{const k=l.c+'|'+(l.m||'');if(!seen.has(k)&&r.length<6){seen.add(k);r.push(l)}});return r.length?`<div class="ms" style="margin-top:8px">${r.map(l=>`<button class="mb" onclick="qf(${l.c},${JSON.stringify(l.m||'').replace(/"/g,'&quot;')},${l.a})">${l.m||catName(l.c)} ${Y(l.a)}</button>`).join('')}</div>`:''};
function qf(c,m,a){$('lc').value=c;$('lm').value=m;$('la').value=a;$('la').focus()}
function addL(){const a=+$('la').value;if(!a)return alert('金額を入れてください');add('led',{d:$('ld').value,c:+$('lc').value,a,m:$('lm').value});$('la').focus()}
function addB(){const a=+$('ba').value,n=$('bn').value.trim();if(!n||!a)return alert('名前と金額を入れてください');add('big',{ym,n,a,ap:false,pm:'card',b:pbank(),c:S.cards[0]?S.cards[0].id:0,memo:''})}
document.addEventListener('toggle',e=>{const t=e.target.dataset&&e.target.dataset.t;if(t)OPN[t]=e.target.open},true);
document.addEventListener('change',e=>{const el=e.target,p=el.dataset.p;if(!p)return;const q=p.split('.'),v=el.type=='checkbox'?el.checked:(el.type=='number'||el.dataset.n)?+el.value:el.value;
if(q[0]=='ob'){S.ob=S.ob||{};(S.ob[q[1]]=S.ob[q[1]]||{})[q[2]]=el.value===''?'':+el.value}else if(q[0]=='ct'){const k=calc(q[1],openB()).cards.find(x=>x.id==q[2]);(S.m[q[1]]=S.m[q[1]]||{})['c'+q[2]]=v-k.fx}else if(q[0]=='rv'){S.rec.find(x=>x.id==q[1]).v[q[2]]=el.value===''?'':+el.value}else if(q[0]=='mv'){(S.m[q[1]]=S.m[q[1]]||{})[q[2]]=v}else if(q[0]=='o')S[q[1]][q[2]]=v;else if(q[0]=='r'){S[q[1]]=v;if(q[1]=='fo'&&v)S.fx.sort((a,b)=>fk(a)-fk(b))}else S[q[0]].find(x=>x.id==q[1])[q[2]]=v;save();go()});
window.KK={get:()=>S,set:(v,at)=>{S=v;mig();try{localStorage.setItem('kk2',JSON.stringify(S));localStorage.setItem('kk2t',at)}catch(e){}go()}};
go();
